### PR TITLE
Making sure to close udp connection.

### PR DESCRIPTION
**Pull request by captncraig**
I believe everywhere that creates a new transport calls RoundTrip exactly once. To avoid zombie connections, just have RoundTrip close the connection when it is done.

### CODE REVIEW

**Comment by captncraig** [comment]
This makes a transport single-use only, but it was only being used that way anyhow.

**Comment by mjibson** [comment]
Yes, I agree that this would fix it, but only because newTransport isn't exported. I think a more correct change would be to add a net.Dialer propertey instead of net.Conn. Then RoundTrip can open and close each connection. You don't have to worry about things being called twice (even though they aren't, but maybe one day)?

I think this whole library needs a massive API change. Transport and other externally useless types should be unexported (Request, Response, Binding, RoundTripper). This should just be Get, Walk, and Rows, since those are what are useful to users.

**Comment by gbrayut** [comment]
FYI: on Windows you can monitor the udp open listeners using the following in powershell:

netstat -p UDP -a -b | select-string scollector | measure -line

We saw this increasing by 1 every 15 seconds until all listener ports were exhausted causing DNS lookups to fail.

**Comment by tlimoncelli** [comment]
I agree the connection should be closed after receiving a reply.  However, what if a reply is never received?  We could accumulate many open connections over the run of a program, or end up with a situation where we have port exhaustion only when we also have outages... which would be 2 bad things happening at once.  

Better practices would be:
1.  Close the connection immediately after getting a reply, or after n seconds. If SNMP doesn't reply in n=10 seconds, we're never going to get a reply.
2.  Always open a single UDP listener, have all replies go to it.  The downside is that now this listener has to disambiguate all replies and match them up with the requests.

I'm curious why Linux doesn't have this problem.  First, does it have this problem but there is some reason why we aren't seeing it?  Second, if Unix doesn't have this problem, why? Does it do (1) above automatically?  if so, how can we replicate that behavior.

**Comment by captncraig** [comment]
@tlimoncelli 
https://github.com/captncraig/snmp/blob/close/snmp.go#L246 sets the read deadline to 5 seconds.

**Comment by tlimoncelli** [comment]
@captncraig  Awesome!  (I'm still curious why/if this problem appears on Unix)

**Comment by mjibson** [comment]
I also just realized that this would have been broken for Walk requests, since they do multiple requests on the same transport, and thus the 2nd and subsequent requests would have used the closed connection. However that wasn't apparent until I refactored the entire codebase.

**Comment by masiulaniec** [comment]
Just wanted to say I am happy to see this package evolve. What I published was just a checkpoint that never got any serious use. My plans had changed but I published it anyway in hope that it could serve as a starting point for someone. Excited to see it has happened!

**Pull request closed without merging**
